import Link from "next/link";
import Formula from "@/components/Formula";
import LessonNav from "@/components/LessonNav";
import RichText from "@/components/RichText";
import Section from "@/components/Section";
import ParallelWireForce from "@/components/interactives/ParallelWireForce";
import PredictionQuestion from "@/components/interactives/PredictionQuestion";
import { TeacherModeProvider, TeacherModeToggle, TeacherNote } from "@/components/interactives/TeacherMode";

export const metadata={title:"Сила между два успоредни проводника · SingularityLab"};
const NAV=[{id:"idea",n:"§1",label:"Механизмът"},{id:"derive",n:"§2",label:"Извеждане"},{id:"direction",n:"§3",label:"Посока"},{id:"pair",n:"§4",label:"Двойката"},{id:"applications",n:"§5",label:"Приложения"},{id:"problems",n:"§6",label:"Задачи"},{id:"recap",n:"§7",label:"Обобщение"}] as const;

const tasks=[
  {title:"Два лабораторни проводника",problem:"Проводници на 5.0 cm носят еднакви токове 20 A в една посока. Намерете F/L.",hint:"Използвайте μ₀I₁I₂/(2πd).",solution:"F/L = 2×10⁻⁷·20·20/0.05 = 1.6×10⁻³ N/m. Токовете са еднакво насочени ⇒ привличане."},
  {title:"Силови шини",problem:"Две шини носят по 5.0 kA в противоположни посоки и са на 20 cm. Каква сила действа на 1 m от всяка шина?",hint:"Противоположните токове се отблъскват; силата върху дължина L е (F/L)L.",solution:"F/L = 2×10⁻⁷·(5000)²/0.20 = 25 N/m. Върху 1 m действа 25 N, насочена навън."},
  {title:"Трети проводник в средата",problem:"Два външни проводника носят еднакви токове I в една посока. Трети е точно по средата и носи ток в същата посока. Каква е резултантната сила върху него?",hint:"Разгледайте силата от левия и десния проводник поотделно.",solution:"Двете сили са равни и противоположни, затова резултантната е нула. Равновесието обаче не е устойчиво при странично отклонение."},
  {title:"Проектиране на разстояние",problem:"Два кабела носят 100 A и 150 A в една посока. Колко далеч трябва да са, за да бъде F/L ≤ 0.010 N/m?",hint:"Изолирайте d от формулата.",solution:"d ≥ μ₀I₁I₂/(2π·0.010) = 2×10⁻⁷·100·150/0.010 = 0.30 m."},
];

export default function ParallelWiresPage(){return <TeacherModeProvider><main className="mx-auto max-w-3xl px-5 pb-24">
  <header className="pt-11 pb-2"><nav aria-label="Път до урока" className="flex items-center gap-2 text-[12px] font-semibold uppercase tracking-[.22em] text-muted"><Link href="/physics">Физика</Link><span>·</span><Link href="/physics?level=university#magnetism">Магнетизъм</Link></nav><h1 className="mt-2 mb-2 font-serif text-[clamp(34px,7vw,48px)] leading-[1.08] font-bold text-ink">Сила между два успоредни проводника</h1><p className="text-[17px] text-muted">Как токът в единия проводник създава поле, което действа върху тока в другия — привличане, отблъскване и инженерни натоварвания</p></header>
  <LessonNav items={NAV} right={<TeacherModeToggle/>}/>
  <Section id="idea" n="§1" title="Единият създава поле, другият го усеща"><p className="text-[18px] text-ink">Два проводника не си действат „директно“. Токът <RichText text="$I_1$" /> създава магнитно поле <RichText text="$\vec B_1$" /> в мястото на втория проводник. После движещите се заряди във втория изпитват силата на Лоренц, която макроскопично е <RichText text="$I_2\vec L\times\vec B_1$" />.</p><div className="mt-5"><PredictionQuestion prompt="Два успоредни проводника носят токове в една и съща посока. Ще се привличат или отблъскват?" options={[{text:"Привличат се",correct:true},{text:"Отблъскват се",correct:false},{text:"Няма сила",correct:false}]} explanation="Полето на първия при втория и посоката на I₂ дават сила към първия. По същия начин първият е привлечен към втория."/></div><TeacherNote><p>Разделяйте причинната верига на две: I₁ → B₁; после I₂×B₁ → F₂. Това е по-надеждно от заучаването „еднакви привличат“.</p></TeacherNote></Section>
  <Section id="derive" n="§2" title="Извеждане на силата на единица дължина"><p className="text-ink/90">За дълги прави проводници на разстояние d използваме полето от първия:</p><div className="my-4"><Formula latex={String.raw`B_1(d)=\frac{\mu_0I_1}{2\pi d}`}/></div><p className="text-ink/90">Вторият проводник е перпендикулярен на това поле, така че силата върху дължина L е:</p><div className="my-4"><Formula latex={String.raw`F_2=I_2LB_1=I_2L\frac{\mu_0I_1}{2\pi d}`}/></div><Formula latex={String.raw`\boxed{\frac FL=\frac{\mu_0I_1I_2}{2\pi d}}`}/><ul className="mt-5 list-disc space-y-2 pl-5 text-ink/90"><li>силата е пропорционална на произведението на токовете;</li><li>намалява като 1/d;</li><li>формулата предполага проводници, много по-дълги от разстоянието между тях.</li></ul></Section>
  <Section id="direction" n="§3" title="Привличане или отблъскване"><ParallelWireForce/><TeacherNote><p>Нека ученикът обръща само единия ток и да предсказва промяната преди бутона. Проверка: обръщането и на двата тока запазва привличането.</p></TeacherNote></Section>
  <Section id="pair" n="§4" title="Двете сили са една двойка"><p className="text-ink/90">Полето на първия действа върху втория, а полето на втория — върху първия. Големините са равни:</p><div className="my-5"><Formula latex={String.raw`\frac{F_1}{L}=\frac{\mu_0I_1I_2}{2\pi d}=\frac{F_2}{L},\qquad \vec F_1=-\vec F_2`}/></div><p className="text-ink/90">Това е конкретна електромагнитна реализация на третия закон на Нютон за стационарната конфигурация. При еднакви посоки системата може да намали магнитната си енергия, като проводниците се приближат; при противоположни — като се отдалечат.</p><div className="mt-5 rounded-r-lg border-l-4 border-plus bg-hl px-4 py-3 text-[15px]"><strong>Историческа бележка:</strong> до 2019 г. амперът е бил дефиниран чрез силата между идеални успоредни проводници. Днес SI фиксира стойността на елементарния заряд e, но този опит остава прекрасна физична реализация.</div></Section>
  <Section id="applications" n="§5" title="Къде тази сила има значение"><div className="space-y-3">{[["Силови шини","При токове от хиляди ампери силите могат да огъват и разкъсват шините при късо съединение; механичните опори се оразмеряват за тях."],["Електропроводи","Проводниците на една фаза и различните фази изпитват променливи сили, които могат да предизвикват вибрации."],["Плазмен pinch","Паралелни токови нишки се привличат и могат да свиват плазмата към оста."],["Определяне на ток","Измерването на магнитната сила е исторически и практически начин електрична величина да се свърже с механична."]].map(([t,x])=><div key={t} className="rounded-[10px] border-[1.5px] border-ink bg-surface px-5 py-4"><span className="text-[11px] font-bold uppercase tracking-[.15em] text-minus">{t}</span><p className="mt-1 text-[15px] text-ink/90">{x}</p></div>)}</div></Section>
  <Section id="problems" n="§6" title="Самостоятелни практически задачи"><div className="space-y-4">{tasks.map((t,i)=><div key={t.title} className="rounded-[10px] border-[1.5px] border-ink bg-surface px-5 py-4"><span className="text-[11px] font-bold uppercase tracking-[.15em] text-plus">Задача {i+1}</span><h3 className="mt-1 text-[17px] font-bold">{t.title}</h3><p className="mt-2 text-ink/90">{t.problem}</p><details className="mt-3 rounded-lg border border-rule px-3 py-2"><summary className="cursor-pointer font-semibold">Подсказка</summary><p className="mt-2 text-[14px] text-muted">{t.hint}</p></details><details className="mt-2 rounded-lg border border-rule px-3 py-2"><summary className="cursor-pointer font-semibold">Решение</summary><p className="mt-2 text-[14px] text-ink/90">{t.solution}</p></details></div>)}</div></Section>
  <Section id="recap" n="§7" title="Обобщение"><div className="rounded-[10px] border-[1.5px] border-ink bg-surface px-5 py-4 shadow-hard"><ul className="list-disc space-y-2 pl-5 text-[15.5px] text-ink/90"><li>Всеки проводник създава B в мястото на другия.</li><li>Силата следва от <RichText text="$I\vec L\times\vec B$" />.</li><li>Еднакво насочени токове се привличат; противоположни се отблъскват.</li><li><RichText text="$F/L=\mu_0I_1I_2/(2\pi d)$" />.</li><li>Силите върху двата проводника са равни и противоположни.</li></ul></div><p className="mt-5 text-ink/90"><strong>Следва:</strong> въртящ момент върху токов контур и магнитен диполен момент — как двойка сили превръща тока в електромотор.</p></Section>
  </main></TeacherModeProvider>}
